#' Finds rows of post-hoc tests summary table in which pairs of treatment groups differ in the
#' levels of only one factor
#'
#' This function identifies the rows in a post-hoc tests summary table (a dataframe object),
#' generated by \code{\link{makeSummaryTable}}, that correspond to comparisons between pairs of factorial
#' treatment combinations in which all but one of the levels are equal. Put another way, the two
#' factorial treatment combinations differ in the levels of only one (and the same) factor in each
#' treatment.
#'
#' @param comparisonNames a vector of character strings containing the names of the
#' treatment combinations being contrasted in each pairwise comparison of means. The first column of
#' the post-hoc tests summary table generated by \code{\link{makeSummaryTable}} produces the
#' type of input required.
#' @param sepChar the character used to concatenate the factor levels in each treatment
#' combination in \code{comparisonNames}.
#' @return a numeric vector of the rows of interest in the post-hoc tests summary table.
#' @author Katya Ruggiero
#' @details The row numbers returned by this function
#' may be used to extract a subset of rows in the post-hoc tests summary table
#' generated by \code{makeSummaryTable} which contain only those pairwise treatment
#' comparisons which differ by exactly one factor level.
#'
#' @seealso \code{\link[predictmeans]{predictmeans}}
#' @seealso \code{\link[meantable]{makeSummaryTable}}
#' @seealso \code{\link[meantable]{makeComparisonNames}}
#' @importFrom Matrix diag
#' @export
#' @examples
#' library(predictmeans)
#' library(nlme)
#' Oats$nitro <- factor(Oats$nitro)
#' fm <- lme(yield ~ nitro*Variety, random=~1|Block/Variety, data=Oats)
#'
#' # library(lme4)
#' # fm <- lmer(yield ~ nitro*Variety+(1|Block/Variety), data=Oats)
#'
#' pm <- predictmeans(fm, "nitro:Variety", pairwise=TRUE, plot = FALSE)
#' oats.tab <- makeSummaryTable(pm)
#'
#' rowsKeep <- getFixedLevelComparisons(oats.tab[,1], sepChar = ",")
#' oats.tab[rowsKeep,]


getFixedLevelComparisons <- function(comparisonNames, sepChar){

  trtCombination.list <- strsplit(as.character(comparisonNames), split = "-")
  trtCombination.mat <- do.call('rbind', trtCombination.list)
  tmp.list <- apply(trtCombination.mat, 2, function(trt) strsplit(trt, split = sepChar))
  compTrtCombination.list <- lapply(tmp.list, function(x) do.call('rbind', x))

  # find all combinations of treatments in which the levels of n - 1
  # factors are constant in both treatments in the comparison

  nFactors <- length(compTrtCombination.list[[1]][1,])
  nCombinations <- nrow(compTrtCombination.list[[1]])

  fixedCols.mat <- matrix(TRUE, nrow = nFactors, ncol = nFactors)
  diag(fixedCols.mat) <- FALSE

  keepRows <- NULL
  for(i in 1:nFactors){

    keep.mat <- compTrtCombination.list[[1]][,fixedCols.mat[i,]] == compTrtCombination.list[[2]][,fixedCols.mat[i,]]
    keep <- apply(as.matrix(keep.mat), 1, function(x) sum(x) == nFactors - 1)
    keepRows <- c(keepRows, (1:nCombinations)[keep])

  }

  return(keepRows)

}
