#' Creates pairwise treatment comparison names
#'
#' This function creates a character vector of pairwise treatment comparison names using the
#' dimension names of a matrix object such as the \code{Pairwise LSDs} and \code{Pairwise p-value}
#' matrices generated by the \code{predictmeans()} function in the \code{predictmeans} package.
#'
#' @param mat is any square symmetric matrix with row and column names being treatment (or
#' factorial treatment combination) names. See \code{Details} below.
#' @return a character vector of all pairwise treatment comparisons names
#' @author Katya Ruggiero
#' @details
#' Although a standalone function, it was primarily developed for its call by the
#' \link{makeSummaryTable} function to create a column of character strings defining the pair of
#' treatments being contrasted (i.e. the pairwise comparisons of means) in the summary table.
#' In \link{makeSummaryTable}, it uses the dimension names of the \code{Pairwise p-value} matrix
#' (generated by \link[predictmeans]{predictmeans}) to construct a character string comprising the
#' pair of treatment names (for each pairwise comparison of means) concatenated with a minus sign
#' '-' in the middle.
#'
#' Note that this function also works with the p-value matrix generated by the
#' \code{predictparallel.asreml()} function in the \code{asremlPlus} package.
#'
#' @seealso \code{\link[predictmeans]{predictmeans}}
#' @export
#' @examples
#' library(ggplot2)
#' library(nlme)
#' library(predictmeans)
#'
#' Oats$nitro <- factor(Oats$nitro)
#' fm <- lme(yield ~ nitro*Variety, random=~1|Block/Variety, data=Oats)
#'
#' library(lme4)
#' fm <- lmer(yield ~ nitro*Variety+(1|Block/Variety), data=Oats)
#' pm <- predictmeans(fm, "nitro:Variety", pairwise=TRUE, plot = FALSE)
#' makeComparisonNames(pm$"Pairwise p-values")

makeComparisonNames <- function(mat){

  trtNames <- colnames(mat)
  # Paste pairs of names with "-" between them to show comparison
  comparison <- NULL
  k <- 1
  for(i in 1:(length(trtNames)-1))
    for(j in (i+1):length(trtNames)){
      comparison[k] <- paste(trtNames[i], "-", trtNames[j], sep="")
      k <- k+1
    }
  comparison

}

