#' Generate means plot with Least Significant Difference (LSD) bar(S)
#'
#' A ggplot2 wrapper function which generates a plot of predicted means with LSD bar(s). It allows
#' a matrix of panels defined by row and column facetting variables. This function requires as its
#' first argument a list of the form generated by the \link{makeLSDlist} function.
#'
#' @param lsdList a list of objects (dataframes and vectors) of the form generated by the
#' \link{makeLSDlist}. The first object must be a predicted means dataframe, with a column for each
#' factor specified in the \code{modelterm} argument in the \link[predictmeans]{predictmeans}
#' function and a one row for each combination of the factor levels.
#' @param y column name (a character string) containing predicted means in \code{lsdList[[1]]},
#' i.e. the first object (a dataframe) in \code{lsdList}.
#' @param x column name (a character string) of variable (factor) in \code{lsdList[[1]]} to be
#' plotted on the x-axis.
#' @param facets character vector of factor names whose levels define a matrix of row and/or column
#' panels in the plot. This vector must be of length 2. Thus, if only one facet factor is needed,
#' fill the vector with the character string \code{"."} (see Examples below). The order of the
#' factor names, one of which may be the character string \code{"."}, determine whether the levels
#' are displayed in rows or columns, with first element (factor name) corresponding to row panels
#' and the second to column panels.
#' @param yLabel y-axis label (character string)
#' @param xLabel x-axis label (character string)
#' @param shape factor name (character string); if supplied, assigns pre-defined shapes to the
#' plotting characters for each of the factor's levels.
#' @param colour factor name (character string); if supplied, assigns pre-defined colour to the
#' plotting characters for each of the factor's levels.
#' @param pointSize numeric value for size of plotting characters
#' @param lineType factor name (character string); if supplied, assigns pre-defined line type to the
#' for each of the factor's levels.
#' @param lineWidth numeric value for width of line used for LSD bars and for any line geometries
#' @param axisLabelSize axis label text size in pts
#' @param tickMarkLabelSize tick label text size in pts
#' @param xTickLabelAngle angle (0, 45 or 90; default 0) of x-axis tick labels
#' @param xStripTextSize x strip text size in pts
#' @param yStripTextSize y strip text size in pts
#' @param legendKeyWidth width of legend key in cms
#'
#' @export
#' @importFrom nlme lme
#' @importFrom lme4 lmer
#' @importFrom predictmeans predictmeans
#' @importFrom reshape melt
#' @examples
#' #' # fruitfly data: factorial with added control
#' data(fruitfly)
#' # -- set up factors
#' newfruitfly <- transform(fruitfly, Type = factor(Type, levels=c(9,0,1),
#'                                    labels=c("Control", "Newly pregnant", "Virgin")))
#' newfruitfly$Partners <- factor(newfruitfly$Partners)
#' newfruitfly$Control <- factor(ifelse(newfruitfly$Type=="Control", "Yes", "No"))
#' # -- fit model
#' fruitfly.lm <- lm(Longevity ~ Control/(Partners*Type), data=newfruitfly)
#' # -- perform post-hoc tests
#' fruitfly.pm <- predictmeans(fruitfly.lm, modelterm = "Control:Partners:Type",
#'                             pairwise = TRUE, plot = FALSE)
#' # -- get table of predicted means
#' fruitfly.m2df <- means2df(fruitfly.pm)
#' # -- create post-hoc tests summary table
#' fruitfly.tab <- makeSummaryTable(fruitfly.pm)
#' # -- replace single comparison name with individual columns
#' ffCompNames.df <- comparisonNames2df(fruitfly.tab$Comparison, split.at=":",
#'                                      varNames = c("Control", "Partners", "Type"))
#' newfruitfly.tab <- data.frame(ffCompNames.df, fruitfly.tab[,-1])
#' newfruitfly.list <- makeLSDlist(fruitfly.m2df, y="Mean", x="Type", eqLevelFactors = "Partners",
#'             LSD=8.29, edgeWidth = 0.05)
#'
#' # -- generate means and LSDs plot
#' meansLSDplot(lsdList =newfruitfly.list, x = "Type", y = "Mean")
#'
#' # -- specify x- and y-axis labels
#' meansLSDplot(lsdList =newfruitfly.list, x = "Type", y = "Mean",
#'              xLabel = "Type of partner", yLabel = "Predicted mean")
#'
#' # -- colour points by Partners
#' meansLSDplot(lsdList =newfruitfly.list, x = "Type", y = "Mean",
#'              xLabel = "Type of partner", yLabel = "Predicted mean",
#'              colour = "Partners")
#'
#' # -- shape points by Partners
#' meansLSDplot(lsdList =newfruitfly.list, x = "Type", y = "Mean",
#'              xLabel = "Type of partner", yLabel = "Predicted mean",
#'              shape = "Partners")
#'
#' # -- colour and shape points by Partners
#' meansLSDplot(lsdList =newfruitfly.list, x = "Type", y = "Mean",
#'              xLabel = "Type of partner", yLabel = "Predicted mean",
#'              colour = "Partners", shape = "Partners")
#'
#' # -- define shapes of points and line types by Partners
#' meansLSDplot(lsdList =newfruitfly.list, x = "Type", y = "Mean",
#'              xLabel = "Type of partner", yLabel = "Predicted mean",
#'              shape = "Partners", lineType = "Partners")
#'
#' # bugs data: weighted least squares analysis of baseline concentration in rat lymph
#' data(bugs)
#'
#' # -- log-transform response
#' bugs$logBaseline <- log(bugs$Baseline + 1)
#'
#' # -- get weights
#' var.mat <- with(bugs, tapply(logBaseline, list(State, Bacteria), var))
#' var.df <- melt(var.mat)
#' names(var.df) <- c("State", "Bacteria", "Var")
#' newbugs <- merge(bugs, var.df)
#' newbugs$Weight <- 1/newbugs$Var
#'
#' # -- weighted least squares two-way ANOVA
#' baselineBugs.lm <- lm(logBaseline ~ State*Bacteria, data = newbugs, weights = Weight)
#' anova(baselineBugs.lm)
#'
#' # -- get predicted means and post-hoc test summary tables
#' baselineBugs.pm <- predictmeans(baselineBugs.lm, modelterm = "State:Bacteria",
#'                                 pairwise=TRUE, plot = FALSE)
#' bugs.m2df <- means2df(baselineBugs.pm)
#' baselineBugs.tab <- makeSummaryTable(baselineBugs.pm)
#' compNames.df <- comparisonNames2df(baselineBugs.tab$Comparison, split.at = ":",
#'                                    varNames = c("State", "Bacteria") )
#' newbaseBugs.tab <- data.frame(compNames.df, baselineBugs.tab[,-1])
#' keeprows <- whichComparison(compNames.df, contrFactor="State")
#' newbaseBugs.tab2 <- newbaseBugs.tab[keeprows,]
#'
#' # -- compute min, max and average LSD by Bacterial strain
#' newbaseBugs.lsd <- getLSDsummary(data = newbaseBugs.tab2, lsdVar = "LSD", by = "Bacteria1")
#'
#' # -- create list needed to plot means and LSDs
#' newbaseBugs.list <- makeLSDlist(meansData = bugs.m2df, y = "Mean", x = "State",
#'                                 LSD = newbaseBugs.lsd, eqLevelFactors = "Bacteria",
#'                                 lsdVar = "LSD_avg", edgeWidth = 0.1)
#' # plot means with LSD bars, facetting by Bacteria
#' meansLSDplot(lsdList = newbaseBugs.list, x = "State", y = "Mean", facets = c("Bacteria","."),
#'              xLabel = "Disease state", yLabel = "Predicted mean")
#'
#' # change font size and orientation of x-axis tick labels
#' meansLSDplot(lsdList = newbaseBugs.list, x = "State", y = "Mean", facets = c("Bacteria","."),
#'              xLabel = "Disease state", yLabel = "Predicted mean", tickMarkLabelSize = 11,
#'              xTickLabelAngle = 90)
#'
#' # bugs data: mixed model analysis of bacterial concentration across time (ignoring baseline)
#' data(bugs)
#'
#' # -- log-transform response
#' bugs$logCells <- log(bugs$Cells + 1)
#'
#' # convert Rat and Time to factors
#' bugs <- toFactor(bugs, variables = c("Rat", "Time"))
#'
#' # fit mixed model
#' bugs.lme <- lme(logCells ~ Bacteria*State*Time, random = ~1|Rat, data = bugs)
#' anova(bugs.lme)
#'
#' # -- get predicted means and post-hoc test summary tables
#' bugs.pm <- predictmeans(bugs.lme, modelterm = "Bacteria:State:Time",
#'                         pairwise=TRUE, plot = FALSE)
#' bugs.m2df <- means2df(bugs.pm)
#' bugs.tab <- makeSummaryTable(bugs.pm)
#' compNames.df <- comparisonNames2df(bugs.tab$Comparison, split.at = ":",
#'                                    varNames = c("Bacteria", "State", "Time") )
#' newBugs.tab <- data.frame(compNames.df, bugs.tab[,-1])
#' keeprows <- whichComparison(compNames.df, contrFactor="Time")
#' newBugs.tab2 <- newBugs.tab[keeprows,]
#'
#' # -- compute min, max and average LSD by Bacterial strain and disease State
#' newBugs.lsd <- getLSDsummary(data = newBugs.tab2, lsdVar = "LSD",
#'                              by = c("Bacteria1", "State1"))
#'
#' # -- create list needed to plot means and LSDs
#' newBugs.list <- makeLSDlist(meansData = bugs.m2df, y = "Mean", x = "Time",
#'                             LSD = newBugs.lsd, eqLevelFactors = c("Bacteria", "State"),
#'                             lsdVar = "LSD_avg", edgeWidth = 0.05)
#'
#' # plot means with LSD bars, facetting by Bacteria and State
#' meansLSDplot(lsdList = newBugs.list, x = "Time", y = "Mean", facets = c("Bacteria","State"),
#'              xLabel = "Time (hours)", yLabel = "Predicted mean",
#'              tickMarkLabelSize = 11, xTickLabelAngle = 90) +
#'              geom_line(data = newBugs.list[[1]], size = 0.9)
#'
#' # average LSD over bacterial strains
#' newBugs.list2 <- makeLSDlist(meansData = bugs.m2df, y = "Mean", x = "Time",
#'                              LSD = newBugs.lsd, eqLevelFactors = "Bacteria",
#'                              lsdVar = "LSD_avg", edgeWidth = 0.05)
#'
#' # plot means facetting only by bacterial strain, using different line types for disease states
#' meansLSDplot(lsdList = newBugs.list2, x = "Time", y = "Mean", facets = c("Bacteria", "."),
#'              xLabel = "Time (hours)", yLabel = "Predicted mean", shape = "State",
#'              lineType = "State", tickMarkLabelSize = 11, xTickLabelAngle = 90,
#'              xStripTextSize = 10, legendKeyWidth = 1.2)
#'
meansLSDplot <- function(lsdList, y, x, facets, yLabel, xLabel, shape, colour, pointSize = 2.5,
                         lineType, lineWidth = 0.9, axisLabelSize = 14, tickMarkLabelSize = 12,
                         xTickLabelAngle = 0, xStripTextSize = 12, yStripTextSize = 12,
                         legendKeyWidth = 1)
{

  p <- ggplot(mapping = aes_string(y = y, x = x))
  p <- if(!missing(shape) & !missing(colour))
         p + geom_point(data = lsdList[[1]], aes_string(shape = shape, colour = colour),
                        size = pointSize)
       else if(!missing(shape) & missing(colour))
         p + geom_point(data = lsdList[[1]], aes_string(shape = shape), size = pointSize)
       else if(missing(shape)  & !missing(colour))
         p + geom_point(data = lsdList[[1]], aes_string(colour = colour), size = pointSize)
       else p + geom_point(data = lsdList[[1]], size = pointSize)
  if(!missing(lineType)) p <- p + geom_line(data = lsdList[[1]], aes_string(linetype = lineType),
                                            size = lineWidth)
  if(!missing(xLabel)) p <- p + xlab(xLabel)
  if(!missing(yLabel)) p <- p + ylab(yLabel)
  if (!missing(facets)){

    if(length(facets) > 2) stop("Currently only 2 facets allowed!", call.=FALSE)
    p <- p + facet_grid(reformulate(facets[1], facets[2]), drop = TRUE, scales="free_x")

  }
  p <- p + geom_line(data = lsdList[[5]], aes_string(y="lsdRange", x="x"), size = lineWidth) +
    geom_line(data = lsdList[[6]], aes_string(y="lsdBottom", x="x"), size = lineWidth) +
    geom_line(data = lsdList[[6]], aes_string(y="lsdTop", x="x"), size = lineWidth)

  p <- p + scale_x_continuous(breaks = lsdList[[2]], labels = lsdList[[3]],
                              limits = lsdList[[4]], expand = c(0, 0))
  p <- p + theme_bw() +
    theme(axis.title = element_text(size = axisLabelSize),
          axis.text = element_text(size = tickMarkLabelSize),
          strip.text.x = element_text(size = xStripTextSize),
          strip.text.y = element_text(size = yStripTextSize),
          legend.key.width = unit(legendKeyWidth,"cm"),
          panel.grid.minor = element_blank())

  if(xTickLabelAngle != 0){

    p <- if(xTickLabelAngle == 45)
           p + theme(axis.text.x = element_text(angle=xTickLabelAngle, hjust=1, vjust=1))
         else if(xTickLabelAngle == 90)
           p + theme(axis.text.x = element_text(angle=xTickLabelAngle, hjust=1, vjust=0.5))
  }

  p

}

